apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-workflows-role
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflows"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-workflows-binding
subjects:
- kind: ServiceAccount
  name: default  # Replace with the correct service account name
  namespace: argo-events
roleRef:
  kind: Role
  name: create-workflows-role
  apiGroup: rbac.authorization.k8s.io
