apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: retraining-webhook
spec:
  service:
    name: retraining-webhook
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    trigger-retraining:
      port: "12000"
      endpoint: /retraining
      method: POST
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: retraining-sensor
spec:
  dependencies:
  - name: retraining-webhook-triggered
    eventSourceName: retraining-webhook
    eventName: trigger-retraining
  triggers:
  - template:
      name: payload
      k8s:
        group: ""
        version: v1
        resource: pods
        operation: create
        source:
          resource:
            apiVersion: v1
            kind: Pod
            metadata:
              generateName: payload-
              labels:
                app: payload
              namespace: bigbertha
            spec:
              containers:
              - name: hello
                image: alpine
                command: ["echo"]
                args: ["This is the message you sent me:\n", ""]
              restartPolicy: Never
        parameters:
          - src:
              dependencyName: payload
              dataKey: body.message
            dest: spec.containers.0.args.1