apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      values: |-
        prometheus:
          prometheusSpec:
            ruleSelector:
              matchLabels:
                isPrometheusRule: "true"
            serviceMonitorSelector:
              matchLabels:
                isServiceMonitor: "true"
        prometheus-node-exporter:
          hostRootFsMount:
            enabled: false
        prometheusOperator:
          admissionWebhooks:
            failurePolicy: Ignore
        alertmanager:
          alertmanagerSpec:
            alertmanagerConfigSelector:
              matchLabels:
                isAlertConfig: "true"
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 42.0.3
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true