apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmchatbot
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: llmchatbot
  template:
    metadata:
      labels:
        app: llmchatbot
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.metricsport }}
            - containerPort: {{ .Values.service.appport }}
          env:
            - name: DOWNLOAD_LATER
              value: "{{ .Values.environment.DOWNLOAD_LATER }}"
          resources:
            requests:
              cpu: {{ .Values.resources.cpuRequest }}
              memory: {{ .Values.resources.memoryRequest }}
            limits:
              cpu: {{ .Values.resources.cpuLimit }}
              memory: {{ .Values.resources.memoryLimit }}
