apiVersion: v1
kind: Service
metadata:
  name: llmchatbot
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: llmchatbot
  ports:
    - protocol: TCP
      port: {{ .Values.service.appPort }}
      targetPort: {{ .Values.service.appPort }}
    - protocol: TCP
      port: {{ .Values.service.streamlitPort }}
      targetPort: {{ .Values.service.streamlitPort }}
  type: ClusterIP
