apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: llm-retraining-pipeline
spec:
  entrypoint: llm-retraining-pipeline

  templates:
    - name: llm-retraining-pipeline
      steps:
      - - name: A
          template: model-retraining
      - - name: B
          template: model-benchmarking-gold-generic
          dependencies: [A]
      - - name: C
          template: model-benchmarking-specific
          dependencies: [A]
      - - name: D
          template: model-metrics-logging-mlflow
          dependencies: [B, C]
      - - name: E
          template: model-quality-evaluation
          dependencies: [D]
      - - name: F
          template: model-logging-mlflow
          when: "{{eq .status.outputs.results.E "true"}}"
          dependencies: [E]
      - - name: G
          template: model-deployment
          dependencies: [F]

    - name: model-retraining
      container:
        image: busybox
        command: ["echo", "Step A: Model Retraining"]

    - name: model-benchmarking-gold-generic
      container:
        image: busybox
        command: ["echo", "Step B: Model Benchmarking on Gold Generic Dataset"]

    - name: model-benchmarking-specific
      container:
        image: busybox
        command: ["echo", "Step C: Model Benchmarking on Specific Dataset"]

    - name: model-metrics-logging-mlflow
      container:
        image: busybox
        command: ["echo", "Step D: Model Metrics Logging to MLflow"]

    - name: model-quality-evaluation
      container:
        image: busybox
        command: ["echo", "Step E: Model Quality Evaluation Against Current Model"]

    - name: model-logging-mlflow
      container:
        image: busybox
        command: ["echo", "Step F: Model Logging to MLflow"]

    - name: model-deployment
      container:
        image: busybox
        command: ["echo", "Step G: Model Deployment"]