apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ .Values.sensor.name }}
spec:
  dependencies:
  {{- range .Values.sensor.dependencies }}
    - name: {{ .name }}
      eventSourceName: {{ .eventSourceName }}
      eventName: {{ .eventName }}
  {{- end }}
  triggers:
    - template:
        name: model-retraining-trigger
        workflow: 
          generateName: {{ .Values.sensor.workflow.generateName }}
          template: {{ .Values.sensor.workflow.template }}