apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    prometheus-operator-validated: 'true'
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 42.0.3
    chart: kube-prometheus-stack-42.0.3
    heritage: Helm
    release: kube-prometheus-stack
  name: thumbs-down-count-rule
  namespace: prometheus
spec:
  groups:
  - name: thumbs-down-count-alert
    rules:
    - alert: thumbs_down_count_exceeded
      expr: thumbs_down_count > 2
      for: 5s
      annotations:
        summary: Model retraining required
        description: Model retraining required
        alert.receivers:
          - name: HTTP Receiver
            type: http
            url: "http://retraining-webhook-eventsource-svc.bigbertha.svc"