apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1gi-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/pv-1gi-1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1gi-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/pv-1gi-2

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1gi-3
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/pv-1gi-3

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1gi-4
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/pv-1gi-4

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1gi-5
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/pv-1gi-5

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-2gi-1
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/pv-2gi-1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-2gi-2
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/pv-2gi-2

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-2gi-3
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/pv-2gi-3

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-2gi-4
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/pv-2gi-4

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-2gi-5
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/pv-2gi-5

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-5gi-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/pv-5gi-1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-5gi-2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/pv-5gi-2

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-5gi-3
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/pv-5gi-3

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-10gi-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/pv-10gi-1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-10gi-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/pv-10gi-2

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-10gi-3
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/pv-10gi-3

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-20gi-1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/pv-20gi-1
