apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ .Values.eventsource.name }}
spec:
  service:
    name: {{ .Values.eventsource.service.name }}
    ports: {{ toYaml .Values.eventsource.service.ports | nindent 6 }}
  webhook:
      {{ .Values.eventsource.webhook.triggerName }}:
        port:  "12000" # weird it can't pick up from values.yaml
        endpoint: {{ .Values.eventsource.webhook.endpoint }}
        method: {{ .Values.eventsource.webhook.method }}

